### ISSUE TITLE
environment is not preserved in sheet view

### ISSUE THREAD

**Issue by gh123man** [Jeonhui/FittedSheets-SwiftUI#6]
It seems any `environment` and `environmentObject`s are lost in the sheet view. 
This can easily be observed by changing to dark mode. 

This seems to at least mostly work when using inline mode however:

Regular mode:
<img width="460" alt="Image" src="https://github.com/user-attachments/assets/64405c04-fcd6-4f3b-9cf5-38a20f20f601" />

Inline mode:
<img width="447" alt="Image" src="https://github.com/user-attachments/assets/f264e493-802d-4a29-a004-d775538e4057" />

I believe this mostly stems from presenting in an empty view controller:

```swift
public func makeUIViewController(context: Context) -> UIViewController {
    return UIViewController()
 }
```

However I have not come up with a simple fix.

**Comment by Jeonhui** [comment]
Thank you for raising this issue!
I have checked it, and it is confirmed to work properly in my environment.
The bottom button section in the inline mode image has a white background setting, and thanks to your report, I have fixed it.
Please let me know the detailed environment and code so that I can respond more quickly.


<img width="490" alt="Image" src="https://github.com/user-attachments/assets/ba5fb680-4511-4146-ac91-156e97577115" />

**Comment by gh123man** [comment]
I pulled your changes. 
The issue still appears to occur when not using inline mode:

Note that while the "show sheet" button respects dark mode, the "Sheet content view" does not:

<img width="441" alt="Image" src="https://github.com/user-attachments/assets/d717add0-3a8c-42a6-8dca-9c3f596fa7bf" />

**Comment by gh123man** [comment]
Here is a complete code example (using your simple example) that demonstrates the problem more specifically: 

- Provide an environment object that is referenced in the main view and in the sheet view
- Does not crash in the main view because the environment object is set
- Does crash in the sheet view because the whole environment is lost. Both the environment object, and the color scheme. 

```swift

import SwiftUI
import FittedSheetsSwiftUI

struct SimpleSettingExampleView: View {
    // MARK: - Sheet State Variable
    @State var showFittedSheet: Bool = false
    
    var body: some View {
        VStack {
            SubView() // Does not crash because environment object is preserved.
            // MARK: - Show Sheet Action
            Button {
                showFittedSheet.toggle()
            } label: {
                Text("show sheet")
            }
        }
        .navigationTitle("Simple")
        .navigationBarTitleDisplayMode(.inline)
        // MARK: - Append Fitted Sheet
        .fittedSheet(isPresented: $showFittedSheet,
                     sizes: [.intrinsic, .marginFromTop(100)],
                     sheetView: {
            // MARK: - Sheet Content View
            SubView() // Crashes because environment object is lost
        })
    }
}

class TextHolder: ObservableObject {
    let str: String
    
    init(str: String) {
        self.str = str
    }
}

struct SubView: View {
    @EnvironmentObject var textHolder: TextHolder
    var body: some View {
        Text(textHolder.str)
    }
}

#Preview {
    SimpleSettingExampleView()
        .environmentObject(TextHolder(str: "Hello world"))
}

```

For what it's worth, [I recently solved the same issue in a library I maintain](https://github.com/gh123man/SwiftUI-LazyPager/issues/14). However the fix in this repo is tricky - the issue appears to be that when you call `present` on a dangling `UIViewController`, the environment is lost. 

[I have come up with a partial fix here](https://github.com/Jeonhui/FittedSheets-SwiftUI/compare/main...gh123man:FittedSheets-SwiftUI:try-fix-environment?expand=1) - by using the `SheetViewController` as the root view controller for `UIViewControllerRepresentable`, the environment is preserved. But this somewhat breaks presentation behavior and completely breaks inline mode. Hope this is helpful.

**Comment by Jeonhui** [comment]
I’ll try to fix it.
Please wait a moment.
Thank you for explaining! :)

**Comment by Jeonhui** [comment]
@gh123man 

I have attempted several approaches, including copying the EnvironmentValues from another context, but confirmed that it's not possible to transfer the entire EnvironmentValues as-is.
Additionally, I reviewed the [master branch of the SwiftUI-LazyPager](https://github.com/gh123man/SwiftUI-LazyPager/tree/master) library you provided, and found that the same issue occurs there as well.
Based on this, I suspect this is a limitation or bug within SwiftUI's UIViewControllerRepresentable.
Could you help me look into any other possible solutions or workarounds for this?

The images below show the state after tapping the "Environment Example" button in LazyPagerExample:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/fcb3de4c-5b5e-4bca-a12f-edaeed92710c" />

Development Environment: 
- XCode Version 16.2 (16C5032a), 
- Swift version 6.0.3,
- iPhone16 Pro Simulator(18.2)

**Comment by gh123man** [comment]
Hey! Thanks for getting back to me!

> Additionally, I reviewed the [master branch of the SwiftUI-LazyPager](https://github.com/gh123man/SwiftUI-LazyPager/tree/master) library you provided, and found that the same issue occurs there as well.

Thanks for looking - indeed there was a bug here, but it was my fault. For some reason this worked in the view preview, but not on a real device. I also had forgotten to provide the environment object in the example app 🤦 -[ ive fixed it in this commit](https://github.com/gh123man/SwiftUI-LazyPager/commit/f1a349d7300f6dc9c213691aa69d47873bfc72dc) and now it should be fully working. 

> Could you help me look into any other possible solutions or workarounds for this?

I will keep tinkering. So far the best bet seems to be to just use inline mode as the problem doesn't appear to occur there. 
FWIW - This behavior seems very hard to get right.
